apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lyh0z82w6-java-quarkus
  janus-idp.io/tekton: lyh0z82w6-java-quarkus
  backstage.io/kubernetes-id: lyh0z82w6-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lyh0z82w6-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
